### ISSUE TITLE
LibWallet compilation for Android liblmdb-sys error

### ISSUE THREAD

**Issue by Daniel-Wang** [mimblewimble/grin-wallet#194] opened 2019-07-25 03:23 UTC
I am trying to `cargo build --target aarch64-linux-android --release` the libwallet module.

I am getting this error:
```
error: failed to run custom build command for `liblmdb-sys v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/username/grin-wallet/target/release/build/liblmdb-sys-b6bfc7b665736f9b/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-apple-darwin")
CC_aarch64-linux-android = None
CC_aarch64_linux_android = None
TARGET_CC = None
CC = None
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-apple-darwin")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "aarch64-linux-android-gcc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/Users/username/grin-wallet/target/aarch64-linux-android/release/build/liblmdb-sys-7a2d430dc3c9f3e3/out/mdb/libraries/liblmdb/mdb.o" "-c" "mdb/libraries/liblmdb/mdb.c"
cargo:warning=mdb/libraries/liblmdb/mdb.c:4625:13: warning: implicit declaration of function 'pthread_mutexattr_setrobust' is invalid in C99 [-Wimplicit-function-declaration]
cargo:warning=                        || (rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST))
cargo:warning=                                 ^
cargo:warning=mdb/libraries/liblmdb/mdb.c:4625:49: error: use of undeclared identifier 'PTHREAD_MUTEX_ROBUST'
cargo:warning=                        || (rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST))
cargo:warning=                                                                     ^
cargo:warning=mdb/libraries/liblmdb/mdb.c:9821:33: warning: unused parameter 'env' [-Wunused-parameter]
cargo:warning=mdb_env_get_maxkeysize(MDB_env *env)
cargo:warning=                                ^
cargo:warning=mdb/libraries/liblmdb/mdb.c:10002:10: warning: implicit declaration of function 'pthread_mutex_consistent' is invalid in C99 [-Wimplicit-function-declaration]
cargo:warning=                        rc2 = mdb_mutex_consistent(mutex);
cargo:warning=                              ^
cargo:warning=mdb/libraries/liblmdb/mdb.c:351:37: note: expanded from macro 'mdb_mutex_consistent'
cargo:warning=#define mdb_mutex_consistent(mutex)     pthread_mutex_consistent(mutex)
cargo:warning=                                        ^
cargo:warning=3 warnings and 1 error generated.
exit code: 1
```
The solution seems to be running `"aarch64-linux-android-gcc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-Wall" "-Wextra" "-o" "/Users/username/grin-wallet/target/aarch64-linux-android/release/build/liblmdb-sys-7a2d430dc3c9f3e3/out/mdb/libraries/liblmdb/mdb.o" "-c" "mdb/libraries/liblmdb/mdb.c"` with an additional `-DMDB_USE_ROBUST=0` flag. Is this configurable from either the `cargo build` command or adding something to Cargo.toml?

**Comment by yeastplume** [comment] 2019-07-25 11:17
I'm not sure it's cargo configurable, this package is being drawn in by the `grin-store` crate upstream, which is pulling in `lmdb_zero`: https://github.com/AltSysrq/lmdb-zero. There may be something in the lmdb zero crate upstream, but I'm not sure.

To isolate, can you try just cloning and building the LMDB Zero crate? If you can give exact details of how the fix is applied to that crate, we might be able to better determine how to solve this in our build.

**Comment by Daniel-Wang** [comment] 2019-08-01 01:32
I have put up an issue on lmbd-zero [here](https://github.com/AltSysrq/lmdb-zero/issues/28), referencing for tracking.

Also it seems like Ironbelly has [successfully built](https://github.com/cyclefortytwo/ironbelly/issues/5) for Android, though he seems reluctant to share it with the community.

**Comment by yeastplume** [comment] 2019-09-24 09:04
Have you managed to get past this? Even though the root cause is an LMDB issue it would be handy to have a workaround posted here for posterity.

**Comment by Daniel-Wang** [comment] 2019-10-18 01:39
@yeastplume Sorry for the late response, but no work around yet. Not sure if Ironbelly will be open-sourced at all or if the build process is going to be shared to fix this.

**Comment by yeastplume** [comment] 2019-12-04 12:46
Going to close this for now, but feel free to re-open if this is still an issue for you.

**Closed by yeastplume** 2019-12-04 12:46 UTC
