### ISSUE TITLE
How to validate an income returned by "retrieve_txs"?

### ISSUE THREAD

**Issue by elvinsophus** [mimblewimble/grin-wallet#315] opened 2020-01-27 08:54 UTC
Are transactions returned by "retrieve_txs" guaranteed to be valid?

I received a transaction (as shown at the bottom) whose `tx_type` is `"TxReceived"` and `confirmed` is `true`, but the balance of my wallet (through "retrieve_summary_info") didn't increase.
Is my wallet having issues returning the correct balance or are there any other conditions that I have missed to check?

(The version of my wallet is "v3.0.0".)

Thank you.

```
[{'parent_key_id': '0200000000000000000000000000000000',
  'confirmed': True,
  'fee': None,
  'amount_credited': '4792781286',
  'num_inputs': 0,
  'ttl_cutoff_height': None,
  'messages': {'messages': [{'public_key': '0225a66ee8d3f4311a38d5221da7f4d509a4433f9af3749abf1d6c43b8f07230fa',
     'message': None,
     'message_sig': None,
     'id': '0'},
    {'public_key': '0383999a56ab30af280d104abec195d2569f6347aa47c81e86abe0eb135c8ab494',
     'message': None,
     'message_sig': None,
     'id': '1'}]},
  'kernel_excess': '099793aa9ff341974f32d77b9b5d083c201628d2d91fc89c670f787194372121ec',
  'id': 357,
  'kernel_lookup_min_height': 536946,
  'num_outputs': 1,
  'tx_slate_id': 'b13c54c1-e893-4878-b9c1-96c897825125',
  'amount_debited': '0',
  'payment_proof': None,
  'creation_ts': '2020-01-25T02:33:05.784902348Z',
  'tx_type': 'TxReceived',
  'confirmation_ts': '2020-01-25T02:37:01.296252389Z',
  'stored_tx': None}]
```

**Comment by jaspervdm** [comment] 2020-01-27 17:35
Looking [here](https://grinscan.net/block/536950#k8), the tx was indeed confirmed. Did you by any chance spend the output already?

**Comment by elvinsophus** [comment] 2020-01-28 02:35
Thanks for your reply. But no, that's not possible.
And among many transactions that I have received, there are two other that just behave like the one above-mentioned, all happening in the past few days after I upgraded my wallet to the current version.

**Comment by yeastplume** [comment] 2020-02-26 10:38
@elvinsophus I'm going to close this because the TX was confirmed and there isn't enough info here to say this is an issue in grin-wallet. If you're still seeing this or have more information, please feel free to reopen or contact us on our keybase channels.

**Closed by yeastplume** 2020-02-26 10:38 UTC
