### ISSUE TITLE
Last send transaction never confirmed when used up grin in the wallet

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#135] opened 2019-06-04 13:18 UTC
tested grin-wallet version: v1.1.0-beta.4

when user want use up all the grin in a wallet, he send all the grin to another user.

however the last send transaction never show confirmed locally even when the receiver's output commit is confirmed in blockchain.

**Comment by hashmap** [comment] 2019-06-05 13:28
It's a know issue (can't find it for some reason), the problem is the wallet tracks a tx's state using the change output which doesn't exist in this case

**Comment by jaspervdm** [comment] 2019-06-05 15:26
Yeah, i suggested its better to query the tx status by kernel instead of change output, but it would require a new node api call that does kernel lookup. Havent had the time to work on this myself.

**Comment by yeastplume** [comment] 2019-06-06 09:02
Makes sense, definitely need to address this. In the meantime 'grin wallet check' should fix the issue when this happens

**Comment by bladedoyle** [comment] 2019-06-08 05:39
I also had this issue - see: https://github.com/mimblewimble/grin-wallet/issues/69

**Comment by yeastplume** [comment] 2019-06-27 09:56
Looking back at it, I think the linked issue was closed accidentally, but it's a duplicate of this one anyhow.

**Closed by yeastplume** 2019-06-27 09:56 UTC
