### ISSUE TITLE
re-posting fails with "Wrong response code: 500 Internal Server Error with data Body"

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#153] opened 2019-06-14 21:37 UTC
Errors from the API call
```
2019-06-14 21:37:50,342 [MainThread  ] [ERROR]  Error calling post_tx.  Code: 0 Reason: {'ClientCallback': 'Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body'}
```

Errors from the grin server node:
```
20190614 21:37:47.937 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0951860ff6a74dc41902f08cbe7614b440af0fff2ad629d2847cd0a8c4a9211fd4 with error Not found.
20190614 21:37:47.937 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08707b918dacbc8e5e4990dc1e47ce0c28b879297f3440959953cce7954683d21f with error Not found.
20190614 21:37:47.938 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 087dd75eaa1f0e43bf54f0773ccde17005683c4fd02aa9b0e19fac51727b10c74a with error Not found.
20190614 21:37:47.940 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09f005fa0b76e255ecbb92bce209d73fa2e85e2ce981d728e520b51ca7cc86ea49 with error Not found.
20190614 21:37:47.940 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 087cc2f18a717e958269df875d5a7d5404b1d5a1f66162e254090b3e2f380351f4 with error Not found.
20190614 21:37:47.940 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08a1ac848e69b5446b61f5ddb0be321421821eccd0ebdd08c2c2b1152c505ce5b2 with error Not found.
20190614 21:37:47.940 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08f4fb58ffebceed8670e5a97e0833137f26d81cd9db97da534acc1a73e0029c09 with error Not found.
20190614 21:37:47.941 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08ac2b54488a7f931c401f5384590a325a5b9c450d39bf9bc51209165d0af1593f with error Not found.
20190614 21:37:49.548 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 087cc2f18a717e958269df875d5a7d5404b1d5a1f66162e254090b3e2f380351f4 with error Not found.
20190614 21:37:49.549 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08707b918dacbc8e5e4990dc1e47ce0c28b879297f3440959953cce7954683d21f with error Not found.
20190614 21:37:49.549 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09f005fa0b76e255ecbb92bce209d73fa2e85e2ce981d728e520b51ca7cc86ea49 with error Not found.
20190614 21:37:49.549 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08f4fb58ffebceed8670e5a97e0833137f26d81cd9db97da534acc1a73e0029c09 with error Not found.
20190614 21:37:49.549 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0951860ff6a74dc41902f08cbe7614b440af0fff2ad629d2847cd0a8c4a9211fd4 with error Not found.
20190614 21:37:49.550 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08a1ac848e69b5446b61f5ddb0be321421821eccd0ebdd08c2c2b1152c505ce5b2 with error Not found.
20190614 21:37:49.550 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 087dd75eaa1f0e43bf54f0773ccde17005683c4fd02aa9b0e19fac51727b10c74a with error Not found.
20190614 21:37:49.551 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08ac2b54488a7f931c401f5384590a325a5b9c450d39bf9bc51209165d0af1593f with error Not found.
20190614 21:37:50.338 INFO grin_api::handlers::pool_api - Pushing transaction d0b1a949f842 to pool (inputs: 2, outputs: 2, kernels: 1)
```

Errors in the wallets log:
```
20190614 21:37:48.740 DEBUG grin_wallet_libwallet::internal::updater - Refreshing wallet outputs
20190614 21:37:50.340 ERROR grin_wallet_impls::node_clients::http - Post TX Error: Request error: Wrong response code: 500 Internal Server Error with data Body
20190614 21:37:50.341 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
```

**Comment by krnlx** [comment] 2019-06-15 08:25
same issue.

**Comment by quentinlesceller** [comment] 2019-06-20 20:29
grin-wallet 2.0.0-beta.1 on floonet.

Receiver:
```
grin-wallet --floonet -e listen
...
20190620 20:24:41.882 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /home/ubuntu/.grin/floo/wallet_data/wallet.seed
20190620 20:24:41.883 DEBUG grin_store::lmdb - DB Mapsize for /home/ubuntu/.grin/floo/wallet_data/db/lmdb is 134217728
20190620 20:24:41.885 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190620 20:24:41.885 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:13415.
20190620 20:24:41.885 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20190620 20:25:01.442 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /home/ubuntu/.grin/floo/wallet_data/wallet.seed
20190620 20:25:01.471 DEBUG grin_core::libtx::build - Building output: 10000000000, Commitment(0922e7b445546347469dfa9de22f6bd3e8a044018fda330b4333a4d04a4461ceff)
```

Sender:
```
grin-wallet --floonet send -d http://100.26.68.39:13415 -s smallest -f 10
20190620 20:25:00.358 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
20190620 20:25:00.358 INFO grin_wallet - Using wallet configuration file at /opt/grin-wallet/grin-wallet.toml
20190620 20:25:00.358 INFO grin_wallet - This is Grin Wallet version 2.0.0-beta.1 (git v2.0.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190620 20:25:00.358 DEBUG grin_wallet - Built with profile "release", features "".
Password:
20190620 20:25:01.247 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:25:01.247 DEBUG grin_store::lmdb - DB Mapsize for /opt/grin-wallet/wallet_data/db/lmdb is 134217728
20190620 20:25:01.249 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190620 20:25:01.249 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:25:01.277 DEBUG grin_wallet_libwallet::internal::updater - Refreshing wallet outputs
20190620 20:25:01.300 DEBUG grin_core::libtx::build - Building input (spending coinbase): 60000000000, 030000000000000000000004a200000000
20190620 20:25:01.300 DEBUG grin_wallet_libwallet::internal::selection - Building change outputs: total change: 49992000000 (1 outputs)
20190620 20:25:01.312 DEBUG grin_core::libtx::build - Building output: 49992000000, Commitment(085dca3733ca7f9893a8a72a96891f485301f54061af8896550d27bc551d321e9c)
20190620 20:25:01.408 INFO grin_wallet_controller::command - Tx created: 10.000000000 grin to http://100.26.68.39:13415 (strategy 'smallest')
20190620 20:25:01.408 DEBUG grin_wallet_impls::adapters::http - Posting transaction slate to http://100.26.68.39:13415/v2/foreign
20190620 20:25:01.553 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:25:01.595 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:25:01.614 DEBUG grin_wallet_libwallet::slate - Validating final transaction
20190620 20:25:01.689 DEBUG grin_wallet_libwallet::api_impl::owner - api: post_tx: successfully posted tx: 1049a31b51af, fluff? true
20190620 20:25:01.689 INFO grin_wallet_controller::command - Tx sent ok
Command 'send' completed successfully
```



Node
```
20190620 20:25:01.640 INFO grin_api::handlers::pool_api - Pushing transaction 1049a31b51af to pool (inputs: 1, outputs: 2, kernels: 1)
20190620 20:25:01.686 DEBUG grin_pool::pool - add_to_pool [txpool]: 1049a31b51af (push-api) [in/out/kern: 1/2/1] pool: 0 (at block 13ab3d8ae519)
20190620 20:25:01.687 DEBUG grin_pool::transaction_pool - added tx to reorg_cache: size now 1
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 45.118.135.254:13414
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 46.4.91.48:13414
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 139.162.168.18:13414
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 104.248.175.61:13414
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 198.245.50.26:13414
20190620 20:25:01.687 DEBUG grin_p2p::peer - Send tx kernel hash d12df654e6e1 to 173.230.154.243:13414
20190620 20:25:01.687 DEBUG grin_p2p::peers - broadcast_transaction: 1049a31b51af to 6 peers, done.
20190620 20:25:01.710 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
20190620 20:25:01.766 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
20190620 20:25:01.776 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
20190620 20:25:01.781 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
20190620 20:25:01.791 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
20190620 20:25:01.934 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: d12df654e6e1, msg_len: 32
```

So far so good. But this transaction will never be confirmed. The nodes will display the following logs:
```
20190620 20:26:06.429 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 085dca3733ca7f9893a8a72a96891f485301f54061af8896550d27bc551d321e9c with error Not found.
```

**Comment by quentinlesceller** [comment] 2019-06-20 20:57
Another example:

Sender:
```
grin-wallet --floonet send -d http://X.X.X.X:13415 -s smallest -f 10
20190620 20:54:38.000 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
20190620 20:54:38.001 INFO grin_wallet - Using wallet configuration file at /opt/grin-wallet/grin-wallet.toml
20190620 20:54:38.001 INFO grin_wallet - This is Grin Wallet version 2.0.0-beta.1 (git v2.0.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190620 20:54:38.001 DEBUG grin_wallet - Built with profile "release", features "".
Password:
20190620 20:54:38.835 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:54:38.835 DEBUG grin_store::lmdb - DB Mapsize for /opt/grin-wallet/wallet_data/db/lmdb is 134217728
20190620 20:54:38.836 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190620 20:54:38.837 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:54:38.865 DEBUG grin_wallet_libwallet::internal::updater - Refreshing wallet outputs
20190620 20:54:38.868 DEBUG grin_core::libtx::build - Building input (spending coinbase): 60000000000, 030000000000000000000004a200000000
20190620 20:54:38.868 DEBUG grin_wallet_libwallet::internal::selection - Building change outputs: total change: 49992000000 (1 outputs)
20190620 20:54:38.880 DEBUG grin_core::libtx::build - Building output: 49992000000, Commitment(09b9bcf792f759e826dde675098ff709041935a070eba0d937386fa412d0a9930f)
20190620 20:54:38.974 INFO grin_wallet_controller::command - Tx created: 10.000000000 grin to http://X.X.X.X:13415 (strategy 'smallest')
20190620 20:54:38.974 DEBUG grin_wallet_impls::adapters::http - Posting transaction slate to http://X.X.X.X:13415/v2/foreign
20190620 20:54:39.114 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:54:39.157 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /opt/grin-wallet/wallet_data/wallet.seed
20190620 20:54:39.176 DEBUG grin_wallet_libwallet::slate - Validating final transaction
20190620 20:54:39.243 DEBUG grin_wallet_libwallet::api_impl::owner - api: post_tx: successfully posted tx: 337c80eaad3c, fluff? true
20190620 20:54:39.243 INFO grin_wallet_controller::command - Tx sent ok
Command 'send' completed successfully
```
Receiver:
```
20190620 20:53:49.855 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Debug, min. level: Debug
20190620 20:53:49.855 INFO grin_wallet - Using wallet configuration file at /home/ubuntu/.grin/floo/grin-wallet.toml
20190620 20:53:49.855 INFO grin_wallet - This is Grin Wallet version 2.0.0-beta.1 (git v2.0.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190620 20:53:49.855 DEBUG grin_wallet - Built with profile "release", features "".
Password:
20190620 20:54:29.483 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /home/ubuntu/.grin/floo/wallet_data/wallet.seed
20190620 20:54:29.484 DEBUG grin_store::lmdb - DB Mapsize for /home/ubuntu/.grin/floo/wallet_data/db/lmdb is 134217728
20190620 20:54:29.485 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190620 20:54:29.485 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:13415.
20190620 20:54:29.485 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20190620 20:54:39.030 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /home/ubuntu/.grin/floo/wallet_data/wallet.seed
20190620 20:54:39.051 DEBUG grin_core::libtx::build - Building output: 10000000000, Commitment(08ae4d2652b0b0347f9bda53c2bb7c27751d28bf1016d513b769527ecf95099f24)
```

Node 1:
```
20190620 20:54:39.216 INFO grin_api::handlers::pool_api - Pushing transaction 337c80eaad3c to pool (inputs: 1, outputs: 2, kernels: 1)
20190620 20:54:39.262 DEBUG grin_pool::pool - add_to_pool [txpool]: 337c80eaad3c (push-api) [in/out/kern: 1/2/1] pool: 0 (at block 13ab3d8ae519)
20190620 20:54:39.263 DEBUG grin_pool::transaction_pool - added tx to reorg_cache: size now 1
20190620 20:54:39.264 DEBUG grin_p2p::peer - Send tx kernel hash 39efd3d922c6 to 104.248.175.61:13414
20190620 20:54:39.264 DEBUG grin_p2p::peer - Send tx kernel hash 39efd3d922c6 to 178.62.78.195:13414
20190620 20:54:39.264 DEBUG grin_p2p::peer - Send tx kernel hash 39efd3d922c6 to 100.26.68.39:13414
20190620 20:54:39.264 DEBUG grin_p2p::peer - Send tx kernel hash 39efd3d922c6 to 139.162.168.18:13414
20190620 20:54:39.264 DEBUG grin_p2p::peers - broadcast_transaction: 337c80eaad3c to 4 peers, done.
20190620 20:54:39.273 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: 39efd3d922c6, msg_len: 32
20190620 20:54:39.350 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: 39efd3d922c6, msg_len: 32
20190620 20:54:39.355 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: 39efd3d922c6, msg_len: 32
20190620 20:54:39.365 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: 39efd3d922c6, msg_len: 32
```


Later on another node:

```
20190620 20:55:33.821 DEBUG grin_chain::txhashset::txhashset - Rewind to header 12604d7bf118 at 180967
20190620 20:55:33.821 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 361925, output 512353, kernel 412623
20190620 20:55:33.821 DEBUG grin_chain::txhashset::txhashset - txhashset: merkle_proof: output: Commitment(08753e40998fe320ec62f2dfbc90ea9472b696c620ef0859d308d33904d2babc04)
20190620 20:55:33.822 DEBUG grin_core::core::pmmr::pmmr - merkle_proof  512352, last_pos 512353
20190620 20:55:33.827 DEBUG grin_chain::txhashset::txhashset - Rewind to header 0d62ec225222 at 180969
20190620 20:55:33.827 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 361930, output 512358, kernel 412626
20190620 20:55:33.827 DEBUG grin_chain::txhashset::txhashset - txhashset: merkle_proof: output: Commitment(08302a4680085d19e6a846bab982d987346d28442ab424a8dd66e48b3da5e467ab)
20190620 20:55:33.827 DEBUG grin_core::core::pmmr::pmmr - merkle_proof  512355, last_pos 512358
20190620 20:55:35.616 DEBUG grin_servers::grin::seed - peer_connect: ignore a duplicate request to 183.14.29.67:13414. previous connecting time: 20:55:15.612
20190620 20:55:35.617 DEBUG grin_servers::grin::seed - monitor_peers: on 0.0.0.0:3414, 1 connected (1 most_work). all 336 = 2 healthy + 9 banned + 325 defunct
20190620 20:55:49.009 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09b9bcf792f759e826dde675098ff709041935a070eba0d937386fa412d0a9930f with error Not found.
20190620 20:55:55.620 DEBUG grin_servers::grin::seed - peer_connect: ignore a duplicate request to 79.107.134.33:13414. previous connecting time: 20:55:35.616
```

**Comment by jaspervdm** [comment] 2019-06-20 21:28
@bladedoyle does this error 500 only appear when _re_posting the tx? If so, it is expected behaviour since the tx is already in the mempool.

From discussion with quentin, we think the `Failure to get output for commitment` errors are also expected, since they are change outputs from your wallet from the tx that are not confirmed yet, that the wallet is trying to check the status for. We might want to change the error level of this log message but it is not a problem.

**Comment by bladedoyle** [comment] 2019-08-14 20:40
@yeastplume I dont believe this should be closed without fix.  A 500 error is never a user error.  If this really is a case of user error (its not) then the type of error reported should be corrected.

**Comment by yeastplume** [comment] 2019-08-15 08:28
Has anyone seen this since, particularly in 2.0.0?

**Comment by jaspervdm** [comment] 2019-08-16 21:57
Like I said in my previous comment, I think this is expected behaviour. If the tx is already in the pool, reposting will fail and return an error.

**Comment by DavidBurkett** [comment] 2019-08-16 22:19
> Like I said in my previous comment, I think this is expected behaviour. If the tx is already in the pool, reposting will fail and return an error.

I think the ask is just for a more appropriate error code and possibly message. 500 isn't supposed to be returned for cases of user error.

**Comment by yeastplume** [comment] 2020-01-21 12:06
This has been open a while now, would be nice to clear it.

Given the issues appears to be the error code that the node API is returning, is it safe to say the resolution is to ensure the `post_tx` method returns something other than 500 with a clearer message when the transaction is in the pool? If so we can open an issue and fix within the node.

**Comment by bladedoyle** [comment] 2020-02-19 18:55
This issue is still seen in v3.0.0

**Comment by bladedoyle** [comment] 2020-02-19 18:55
The tx is *not* already in the pool, the tx remains unconfirmed, and it can not be reposted

**Comment by jaspervdm** [comment] 2020-02-19 19:48
I will investigate and try to fix it

**Comment by bladedoyle** [comment] 2020-02-28 19:37
Here is the error from the node when initially attempting to create and post the tx:
`
$ grin-wallet send -d xxx 4.20
Password:
20200226 04:49:18.456 WARN grin_wallet_impls::adapters::http - Starting TOR Process for send at Some(V4(127.0.0.1:59050))
20200226 04:49:35.048 ERROR grin_wallet_impls::node_clients::http - Post TX Error: Request error: Wrong response code: 500 Internal Server Error with data Body
20200226 04:49:35.048 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
20200226 04:49:35.048 ERROR grin_wallet_controller::command - Tx sent fail: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
`

**Comment by jaspervdm** [comment] 2020-03-05 11:24
As of the latest master, the "failure to get output commitment" for not found outputs should no longer appear. It doesn't solve the issue of error 500 responses on tx post but I'm going to keep looking into that. So far I am having troubles reproducing it reliably.

**Comment by jaspervdm** [comment] 2020-03-10 13:38
@bladedoyle @quentinlesceller Does this still occur in latest master? I'm having trouble reproducing it, could you paste your exact node+wallet versions and the steps you followed? I tried the following:
- Submit tx and repost with only outbound peers (NATed)
- Submit tx and repost with both inbound and outbound peers
- Submit tx and repost with `--fluff`
- Send and repost multiple tx in short succession

**Comment by bladedoyle** [comment] 2020-04-02 16:28
I have not seen this since updating to 3.1.1

**Comment by quentinlesceller** [comment] 2020-04-02 17:38
Okay closing then.

**Closed by quentinlesceller** 2020-04-02 17:38 UTC
